name: fook_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+9
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.8.1+7
  image_picker: ^0.8.3+1
  http: ^0.13.3
  dio: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  cached_network_image: ^3.1.0
  google_fonts: ^2.1.0
  shimmer: ^2.0.0
  fluttertoast: ^8.0.8
  day_night_switcher: ^0.2.0+1
  clipboard: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - lib/Assets/add.png
    - lib/Assets/arrow_downward.png
    - lib/Assets/arrow_upward.png
    - lib/Assets/share.png
    - lib/Assets/Wallet_Icon.png
    - lib/Assets/settings-icon 1.png
    - lib/Assets/Subtract.png
    - lib/Assets/football.png
    - lib/Assets/joker.jpg
    - lib/Assets/record.png
    - lib/Assets/camera.png
    - lib/Assets/play.png
    - lib/Assets/user.png
    - lib/Assets/googleLogin.png
    - lib/Assets/Fook.png
    - lib/Assets/eth.png
    - lib/Assets/null.png
    - lib/Assets/email.png
    - lib/Assets/password.png
    - lib/Assets/home.png
    - lib/Assets/redHear.png
    - lib/Assets/magnify.png
    - lib/Assets/profile.png
    - lib/Assets/gallery.png
    #   lib/Assets/esport/esport (1).png
    # - lib/Assets/esport/esport (2).png
    # - lib/Assets/esport/esport (3).png
    # - lib/Assets/euro/euro (1).png
    # - lib/Assets/euro/euro (2).png
    # - lib/Assets/euro/euro (3).png
    # - lib/Assets/fortnite/fortnite (1).png
    # - lib/Assets/fortnite/fortnite (2).png
    # - lib/Assets/fortnite/fortnite (3).png
    # - lib/Assets/rolex/rolex (1).png
    # - lib/Assets/rolex/rolex (2).png
    # - lib/Assets/rolex/rolex (3).png
    # - lib/Assets/rollingstone/image (1).png
    # - lib/Assets/rollingstone/image (2).png
    # - lib/Assets/rollingstone/image (3).png
    # - lib/Assets/ufc/image (1).png
    # - lib/Assets/ufc/image (2).png
    # - lib/Assets/ufc/image (3).png
    # - lib/Assets/grid/image (1).png
    # - lib/Assets/grid/image (2).png
    # - lib/Assets/grid/image (3).png
    # - lib/Assets/grid/image (4).png
    # - lib/Assets/grid/image (5).png
    # - lib/Assets/grid/image (6).png
    # - lib/Assets/grid/image (7).png
    # - lib/Assets/grid/image (8).png
    # - lib/Assets/grid/image (9).png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: Fonts/Montserrat-Medium.ttf
  #         weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
